Create designfile readme.md
Sfayson1/portfolio-website pull request #8
Opened 2024-04-03 13:48 UTC by Sfayson1

first iteration of web app wireframe design

2024-04-03 13:50 UTC, Sfayson1 commented
direct link to wireframe for any notes or necessary corrections. 
https://www.figma.com/file/L6ZvsACUG8n4A99PSudQuS/Untitled?type=design&node-id=111%3A65&mode=design&t=FtfTVpM6nJg2aStE-1

2024-04-08 14:09 UTC, Sfayson1 commented
@jeromehardaway Are you available to review this pull request

2024-04-08 17:20 UTC, jeromehardaway commented
I just reviewed. It seems put in the classic sense which I don't recommend. Remember you won't have projects because you will be putting what you learn as features. I also don't see a blog implementation.

2024-04-08 17:28 UTC, Sfayson1 commented
> I just reviewed. It seems put in the classic sense which I don't recommend. Remember you won't have projects because you will be putting what you learn as features. I also don't see a blog implementation.
The blog section is under the project section. how would you recommend that features be implemented instead?

2024-04-11 15:49 UTC, Sfayson1 commented
@jeromehardaway made corrections to wireframe and also included an image of the wireframe.

2024-04-23 16:44 UTC, jeromehardaway requested changes
Spoke on the changes that needed to be made.

2024-04-23 16:44 UTC, jeromehardaway commented on image-1.png
**LOVE**

2024-04-23 16:44 UTC, jeromehardaway commented on image.png
I think this is supposed to be the secondary pages right? Since you have a strong intro page, this can be cards that lead to single pages such as blog pages. Put the contact on the final page where its just a header image, paragrpah for the CTA and the contact page.

2024-04-26 03:05 UTC, Sfayson1 commented
@jeromehardaway I made the necessary corrections and added the wireframe for the other pages as well.

2024-04-26 05:21 UTC, jeromehardaway approved these changes

2024-04-26 06:21 UTC, merged